"""Custom Prometheus metrics — business-level counters and histograms.

These complement the auto-instrumented HTTP metrics from
`prometheus-fastapi-instrumentator`. The standard `/metrics` endpoint on
the API serves both.

Naming follows Prometheus conventions:
  - snake_case
  - `_total` suffix for monotonic counters
  - `_seconds` suffix for time durations
  - label names lowercase, no high-cardinality values
"""

from prometheus_client import Counter, Gauge, Histogram

# ── Business counters ────────────────────────────────────────────────────────

events_emitted_total = Counter(
    "smartcourse_events_emitted_total",
    "Domain events emitted (written into the outbox or sent direct to Kafka)",
    ["event_type", "path"],   # path = "outbox" | "direct" — separates the two emission paths
)

events_archived_total = Counter(
    "smartcourse_events_archived_total",
    "Events written to the MongoDB `events` collection by the archiver",
    ["event_type"],
)

events_consumed_total = Counter(
    "smartcourse_events_consumed_total",
    "Messages handled by a Kafka consumer (by outcome)",
    ["consumer", "event_type", "outcome"],   # outcome = "enqueued" | "duplicate" | "error"
)

outbox_published_total = Counter(
    "smartcourse_outbox_published_total",
    "Outbox rows successfully published to Kafka by the relay",
    ["event_type"],
)

outbox_pending = Gauge(
    "smartcourse_outbox_pending",
    "Outbox rows waiting for the relay (sent_at IS NULL) — backlog / failure signal",
)


# ── Histograms ───────────────────────────────────────────────────────────────

outbox_latency_seconds = Histogram(
    "smartcourse_outbox_latency_seconds",
    "Time from outbox INSERT to Kafka send (excludes consumer lag)",
    ["event_type"],
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)


# ── LLM / RAG (Week 5) ───────────────────────────────────────────────────────
# The assistant's slowness is the LLM, not retrieval. These make that visible:
# generation wall-time, the prompt-eval lead-in (= the "thinking…" gap before
# the first token), and throughput (tok/s = tokens_total / eval_seconds_sum).

llm_requests_total = Counter(
    "smartcourse_llm_requests_total",
    "LLM chat completions, by model and outcome",
    ["model", "outcome"],   # outcome = "success" | "error" | "cancelled" (client disconnect mid-stream)
)

llm_tokens_generated_total = Counter(
    "smartcourse_llm_tokens_generated_total",
    "Total output tokens generated by the LLM",
    ["model"],
)

llm_generation_seconds = Histogram(
    "smartcourse_llm_generation_seconds",
    "Wall-clock time for a full streamed LLM completion",
    ["model"],
    buckets=(0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0, 300.0),
)

llm_prompt_eval_seconds = Histogram(
    "smartcourse_llm_prompt_eval_seconds",
    "Time the model spent reading the prompt before the first token "
    "(Ollama prompt_eval_duration) — this is the 'thinking…' gap",
    ["model"],
    buckets=(0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0),
)

llm_eval_seconds = Histogram(
    "smartcourse_llm_eval_seconds",
    "Time the model spent generating tokens (Ollama eval_duration). "
    "tok/s = rate(llm_tokens_generated_total) / rate(llm_eval_seconds_sum)",
    ["model"],
    buckets=(0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0, 300.0),
)

# Time-to-first-token (TTFT) — the silence the user actually feels before the
# answer starts streaming. ≈ load + prompt_eval + first-token decode + network.
# Recorded from the Python side (perf_counter delta), not Ollama's own counters,
# so it includes the bits Ollama doesn't measure (HTTP + JSON line buffering).
llm_time_to_first_token_seconds = Histogram(
    "smartcourse_llm_time_to_first_token_seconds",
    "Wall-clock from issuing the chat request to receiving the first token",
    ["model"],
    buckets=(0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0, 300.0),
)

# Prompt size in tokens (Ollama prompt_eval_count). Pairs with
# llm_prompt_eval_seconds to prove the "long prompt → long prefill" relationship
# in a Grafana scatter — the lever for the RAG context-size tuning later.
llm_prompt_tokens = Histogram(
    "smartcourse_llm_prompt_tokens",
    "Prompt length in tokens, as counted by the model's own tokenizer",
    ["model"],
    buckets=(64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384),
)
